# Generated by Django 3.2.1 on 2021-10-29 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content', models.CharField(max_length=256)),
                ('importance', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('category', models.CharField(choices=[('SC', 'School'), ('WK', 'Work'), ('SP', 'Sport'), ('ER', 'Errands'), ('FD', 'Food'), ('MISC', 'Miscelaneous')], default='MISC', max_length=16)),
                ('completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
