# Generated by Django 3.2.8 on 2021-11-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_task_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('school', 'School'), ('coding', 'Coding'), ('work', 'Work'), ('sport', 'Sport'), ('errands', 'Errands'), ('diet', 'diet'), ('miscelaneous', 'Miscelaneous')], default='miscelaneous', max_length=16),
        ),
    ]
